name: tekyz-data-ingestion
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pandas=2.2.3

  # Core ML and embedding dependencies
  - pytorch
  - transformers
  - scikit-learn=1.5.2
  - scipy=1.13.1

  # Web scraping and networking
  - requests=2.32.4
  - beautifulsoup4=4.12.3
  - lxml=5.3.0

  # Data processing utilities
  - tqdm=4.67.1
  - psutil=6.1.0

  # Visualization and plotting
  - matplotlib=3.9.3
  - seaborn=0.13.2

  # Development and utilities
  - python-dotenv=1.0.1

  # Install via pip (not available in conda)
  - pip:
      # Streamlit and UI dependencies
      - streamlit==1.39.0
      - streamlit-option-menu==0.3.6

      # Word document processing
      - python-docx==1.1.2
      - docx2txt==0.8

      # ML and embeddings (latest versions)
      - sentence-transformers==3.3.1
      - torch==2.5.1

      # Vector database
      - qdrant-client==1.14.3

      # Configuration and validation
      - pydantic==2.10.4
      - pydantic-settings==2.7.0

      # Enhanced logging
      - loguru==0.7.3

      # Text processing
      - nltk==3.9.1
      - langdetect==1.0.9
      - readability==0.3.1

      # Additional ML dependencies
      - h5py==3.12.1
      - typing-extensions==4.12.2
      - packaging==24.2

      # Networking
      - urllib3==2.2.3
      - certifi==2024.12.14

      # Browser automation (if needed)
      - selenium==4.27.1
      - fake-useragent==1.5.1
